spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=ekycDB;encrypt=false;integratedSecurity=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

app:
  jwt:
    secret: ZmFrZV9jdG9zX2VreWNfZGVtb19zZWNyZXRfZmFrZV9jdG9zX2VreWNfZGVtbw==
    expiration: 86400000   # 24 hours in ms
    issuer: ekyc-demo
  crypto:
    secret: MySuperSecretKey123456789
  frontend:
    base-url: http://localhost:5173
  backend:
    base-url: http://localhost:8080
  auth:
    email-verify-path: /api/auth/verify-email
    verify-token-exp-minutes: 15
  storage:
    kyc-dir: storage/kyc

server:
  port: 8080

